const CREATE_USER_REPOSITORY_TOKEN = Symbol('CreateUserRepository');
const FIND_USER_BY_EMAIL_REPOSITORY_TOKEN = Symbol('FindUserByEmailRepository');

export { CREATE_USER_REPOSITORY_TOKEN, FIND_USER_BY_EMAIL_REPOSITORY_TOKEN };
