const CREATE_COURSE_REPOSITORY_TOKEN = Symbol('CreateCourseRepository');
const SEARCH_COURSES_REPOSITORY_TOKEN = Symbol('SearchCoursesRepository');

export { CREATE_COURSE_REPOSITORY_TOKEN, SEARCH_COURSES_REPOSITORY_TOKEN };
