const CREATE_COURSE_REPOSITORY_TOKEN = Symbol('CreateCourseRepository');
const SEARCH_COURSES_REPOSITORY_TOKEN = Symbol('SearchCoursesRepository');
const UPDATE_COURSE_REPOSITORY_TOKEN = Symbol('UpdateCourseRepository');
const DELETE_COURSE_REPOSITORY_TOKEN = Symbol('DELETECourseRepository');
const FIND_COURSE_BY_ID_REPOSITORY_TOKEN = Symbol(
  'FindCourseByIdCourseRepository',
);

export {
  CREATE_COURSE_REPOSITORY_TOKEN,
  DELETE_COURSE_REPOSITORY_TOKEN,
  FIND_COURSE_BY_ID_REPOSITORY_TOKEN,
  SEARCH_COURSES_REPOSITORY_TOKEN,
  UPDATE_COURSE_REPOSITORY_TOKEN,
};
