const COURSE_BASE_ROUTE = 'courses';
const CREATE_COURSE_ROUTE = '/';
const SEARCH_COURSE_ROUTE = '/';
const UPDATE_COURSE_ROUTE = '/:id';
const DELETE_COURSE_ROUTE = '/:id';
const FIND_COURSES_USER_ROUTE = '/me';

export {
  COURSE_BASE_ROUTE,
  CREATE_COURSE_ROUTE,
  DELETE_COURSE_ROUTE,
  FIND_COURSES_USER_ROUTE,
  SEARCH_COURSE_ROUTE,
  UPDATE_COURSE_ROUTE,
};
