const COURSE_BASE_ROUTE = 'courses';
const CREATE_COURSE_ROUTE = '/';
const SEARCH_COURSE_ROUTE = '/';
const UPDATE_COURSE_ROUTE = '/:id';

export {
  COURSE_BASE_ROUTE,
  CREATE_COURSE_ROUTE,
  SEARCH_COURSE_ROUTE,
  UPDATE_COURSE_ROUTE,
};
